### ISSUE TITLE
[问题反馈] 如何删除面版

### ISSUE THREAD

**Issue by bin0214** [cyhuajuan/v-space#4]
**描述问题**
目前创建了多个的面版，有部分不使用了，但是找不到删除入口

**期望效果**
可以删除面版

**Comment by cyhuajuan** [comment]
@bin0214  打开书签管理器，左侧其它书签下会有个命名为“侧边栏垂直书签和标签页管理器数据”的文件夹，这个文件夹的下级文件夹就是对应了面板，删除这个文件夹就是删除面板。
