### ISSUE TITLE
是否考虑加个书签搜索功能[功能建议] 

### ISSUE THREAD

**Issue by mouzjnr** [cyhuajuan/v-space#9]
插件定位是书签和侧边栏

可以加个搜索功能。最好是在下部面板切换附近加个全局的搜索 

![06-08_07-38-02](https://github.com/cyhuajuan/vspace/assets/52559103/51bac28f-e26a-4a05-809b-9b92f3394405)

大部分情况侧边栏下部分是用不着的，不会打开几十个标签页 用来放一个全局的搜索框应该不错

**Comment by cyhuajuan** [comment]
一开始有想过搜索功能，最后决定不做，原因主要是通过搜索来找到并打开指定书签页和标签页过于复杂，第一次的优化选择了嵌套标签页，这样可以更方面的找到需要的标签页。至于书签，通过合理的规划面板和文件夹也可以做到快速找到并打开指定的书签页，所以这个插件不会添加搜索功能。

对于书签过多需要快速搜索的场景，我有规划另一款插件，一个页面内的命令面板，可以用于快速搜索书签，不过目前还没有上架。
